services:
    pia-qbittorrent:
        image: gjergjk/pia-qbittorrent:latest
        container_name: pia-qbittorrent
        cap_add:
            - NET_ADMIN
        environment:
            - PIA_REGION=netherlands
            - PIA_USERNAME=
            - PIA_PASSWORD=
            - PORT_FORWARDING=true
            - VPN_CLIENT=wireguard
            - WEBUI_PORT=8888
        volumes:
#            - ./auth.conf:/auth.conf
            - ./config:/config
            - ./downloads:/downloads
        ports:
            - "8888:8888"
        restart: unless-stopped
